
export const newForm = {
    affectedSegregation: null,
    allele: null,
    allele1: null,
    allele2: null,
    alleleInControl: null,
    alleleInPatient: null,
    ancestry: null,
    clinvarPathogenicity: "",
    comment: "",
    confidenceInterval: "",
    confirmed: null,
    controlFreq: "",
    deNovo: null,
    experiment: null,
    funChange: null,
    genotype: null,
    genotypeDesc: null,
    id: null,
    indicator: null,
    inheritance: null,
    keyWords: null,
    lod: '',
    lodUser: null,
    name: "",
    nonsegregation: null,
    oddRatio: "",
    pathogenicity: "",
    patientFreq: "",
    pdf: null,
    phase: "",
    phenotype: null,
    phenotypeDesc: null,
    phenotypeOmim: null,
    phenotypicConsistency: null,
    pmcid: null,
    pmid: "",
    point: "",
    pp1Figure: null,
    pp1LodScore: null,
    proband: 0,
    ps2Point: null,
    sentence: "",
    source: null,
    strength: null,
    title: null,
    totalAlleleInPatient: null,
    totalAlleleInControl: null,
    unaffectedSegregation: null,
    userId: '22',
    variantId: ""
}

export const paperCriteriaForm = {
    baseInfor: {
        user_id: "22",
        pmid: "16460646",
        variant_id: "7-107315505-T-A",
    },
    pm3: {
        id: '',
        strength: '',
        phase: '',
        allele2: '',
        pathogenicity: '',
        proband: 0,
        evidence: ''
    },
    bp2: {
        id: '',
        strength: '',
        phase: '',
        allele2: '',
        pathogenicity: '',
        proband: 0,
        evidence: ''
    },
    ps2: {
        id: '',
        denovo_status: '',
        phenotype: '',
        phenotypic_consistency: '',
        proband: 0,
        evidence: ''
    },
    pp1: {
        id: '',
        phenotype: '',
        inheritance: '',
        affected_segregation: 0,
        unaffected_segregation: 0,
        lod_score: '',
        evidence: ''
    },
    bs4: {
        id: '',
        strength: '',
        phenotype: '',
        inheritance: '',
        genotype: '',
        case: 0,
        evidence: ''
    },
    pp4: {
        id: '',
        strength: '',
        phenotype: '',
        inheritance: '',
        proband: 0,
        evidence: ''
    },
    bp5: {
        id: '',
        strength: '',
        phenotype: '',
        proband: 0,
        evidence: ''
    },
    ps4: {
        id: '',
        phenotype: '',
        allele_in_patient: null,
        total_allele_in_patient: null,
        allele_in_control: null,
        total_allele_in_control: null,
        ancestry: '',
        patient_frequency: '',
        control_frequency: '',
        odd_ratio: '',
        confidence_interval: '',
        inheritance: '',
        proband: 0,
        evidence: ''
    },
    ps3: {
        id: '',
        strength: '',
        experiment: '',
        function_change: '',
        evidence: ''
    }
}